apiVersion: v1
kind: PersistentVolume
metadata:
    name: app-storage
spec:
    storageClassName: "apps"
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    claimRef:
        namespace: default
        name: app-storage-claim
    hostPath:
        path: /home/s_mohamed2102/pv-data
        type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: app-storage-claim
spec:
    storageClassName: "apps"
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi
