apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.2.0
          env:
            - name: xpack.security.enabled
              value: "false"
            - name: SERVER_NAME
              value: "localhost"
            - name: ELASTICSEARCH_HOSTS
              value: "http://35.222.152.101:9200"
            - name: ELASTICSEARCH_URL
              value: "http://35.222.152.101:9200"
              # valueFrom:
              #   configMapKeyRef:
              #     name: elasticsearch-connection-configmap
              #     key: db-connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - port: 5601
      protocol: TCP
      # targetPort: 5601
      # nodePort: 30202
